server:
  port: 8080

# propriedades do servidor de configuracao
spring:
  application:
    name: greeting-service
  config:
    import:
      - optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: prod

# propriedade de configuracao do nivel de exposicao dos endpoints da API
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

greeting-service:
  greeting: "olá"
  default-value: "mundo"
