server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book_service?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: headbangerpf27
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
      url: jdbc:postgresql://localhost:5432/
      schemas: book_service
      user: postgres
      password: headbangerpf27
