server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CRVEdgar/config-server
          #username:
          #password:
          default-label: main
          search-paths:
            - 'greeting-service*'